# Desired state of the "dev" environment.
# image.tag is rewritten by the CI pipeline after every build that passes the security gate.
image:
  registry: localhost:5001
  owner: ratneshvaibhav
  tag: "1.0.1"
backend:
  env:
    APP_ENV: development
    LOG_LEVEL: INFO
