apiVersion: v1
kind: Service
metadata:
  name: cgpa-calculator
  namespace: session16
spec:
  type: NodePort
  selector:
    app: cgpa-calculator
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30001     # published on the laptop by the kind config
