apiVersion: v1
kind: Service
metadata:
  name: {{ include "shelfshare.name" . }}-frontend
  labels:
    {{- include "shelfshare.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  selector: {{- include "shelfshare.selector" (dict "Release" .Release "component" "frontend") | nindent 4 }}
  ports:
    - {name: http, port: 80, targetPort: http}
